Iter18
maybecoding/go-metrics pull request #18
Opened 2024-02-27 20:26 UTC by maybecoding

2024-02-29 16:09 UTC, maxlyaptsev commented on internal/server/handlers/example_test.go
> +	defer ts.Close()
подготовку тут хотелось бы скрыть чтобы упростить чтение полезного кода и остался только запрос

2024-02-29 16:09 UTC, maxlyaptsev commented on internal/server/handlers/example_test.go
> +		fmt.Println("send single gauge message /update/gauge/single/3232.23")
думаю тут лучше комментарии оставлять т.к. они не выглядят как код и не кажутся частью логики

2024-02-29 16:16 UTC, maxlyaptsev commented
В профиле вижу только подключение к базе данных. Нужно дать нагрузку чтобы было что-то видно. Можно искуственно поднять частоту сбора метрик, подержать подольше и т.д.
<img width="646" alt="image" src="https://github.com/maybecoding/go-metrics/assets/10906726/df21c50d-82d2-4656-ac09-ab1952ecf2eb">

2024-03-04 11:15 UTC, maxlyaptsev commented
В агенте все отлично, профиль понятный. Но в серверном ситуация как прежде. Половина уходит на установку соединения. Причем использование памяти очень уж низкое - 500кб
<img width="577" alt="image" src="https://github.com/maybecoding/go-metrics/assets/10906726/234315ab-2420-4991-bfec-0ac947234fe9">

Вот пример, я собрал с твоего сервера профиль памяти:
<img width="719" alt="image" src="https://github.com/maybecoding/go-metrics/assets/10906726/db00247c-f4ed-4d49-bfe9-6679030b2570">

2024-03-04 11:19 UTC, maxlyaptsev requested changes

2024-03-04 11:19 UTC, maxlyaptsev commented on internal/server/handlers/handler.go
>  	"net/http"
В роутере не зарагистрированы pprof хендлеры. Соответственно невозможно снять профиль с рабочего приложения, а только с бенчмарка. Профиль часто снимают с сервиса в продакшене / тестинге т.к. это наиоболее настоящая информация. Бенчмарки показывают только искусственный кейс, да и писать его под каждую ручку сложней чем просто нагрузить сервис и снять профиль

2024-03-04 11:19 UTC, maxlyaptsev commented on Makefile
> +test-10k:
это только один маленький запрос. В реальности на сервер будет идти какой-то RPS - его и следует тут реализовать. Один запрос просто потеряется в объемах старта сервиса

2024-03-04 21:31 UTC, maybecoding commented
Как ты собирал профиль по памяти? Я снимал под постоянной нагрузкой пару минут - аллокаций не более 100 МБ.

2024-03-05 16:30 UTC, maxlyaptsev commented
> Как ты собирал профиль по памяти? Я снимал под постоянной нагрузкой пару минут - аллокаций не более 100 МБ.

запустил серверную часть
несколько раз дернул твои же подготовленные запросы
100Мб это довольно много, но в result.pprof 500Кб и все ушло на инициализацию базы данных

2024-03-05 16:37 UTC, maxlyaptsev commented on cmd/agent/agent_bench_test.go
> +			CollectIntervalSec: 0,
как поведет себя сервис с интервалом 0? Будет ли отправка метрик в этом случае?

2024-03-05 18:15 UTC, maybecoding commented on cmd/agent/agent_bench_test.go
> +			CollectIntervalSec: 0,
Будет собирать без паузы

2024-03-10 10:31 UTC, merged