Iter5
maybecoding/go-metrics pull request #5
Opened 2023-11-06 19:45 UTC by maybecoding

2023-11-07 17:20 UTC, maxlyaptsev requested changes

2023-11-07 17:20 UTC, maxlyaptsev commented on cmd/agent/config/config.go
> +package config
неудачное место для пакета - лучше вынести в internal

2023-11-07 17:20 UTC, maxlyaptsev commented on cmd/server/config/flags.go
> +var serverAddress string
кажется из-за одной строчки не имеет смысла создавать отдельный файл. А еще следует избегать глобальных переменных

2023-11-07 17:20 UTC, maxlyaptsev commented on internal/agent/httpsender/httpSender.go
> +	return func(metrics []*app.Metric) {
а почему не вернуть структуру Sender, а у нее не реализовать метод Send()?
Все таки возвращать в констуркторе функцию не очень читаемо, а расширить ее и добавить новые методы уже не получится

2023-11-07 17:20 UTC, maxlyaptsev commented on internal/server/controller/metricGet.go
> +package controller
по поводу именования файлов - только строчные буквы (_test исключение)

2023-11-07 17:20 UTC, maxlyaptsev commented on internal/agent/memcollector/memCollector.go
> +		metrics[i] = &app.Metric{Type: MetricGauge, Name: mType, Value: strconv.FormatFloat(m, 'f', -1, 64)}
тут можно в слайс положить т.к. ключ по сути не нужен. Не забыть зарезервировать память заранее на количество элементов

2023-11-07 17:20 UTC, maxlyaptsev commented on internal/server/app/interfaces.go
> +type Storage interface {
интерфейсы объявляются в месте использования

2023-11-08 16:45 UTC, maxlyaptsev commented on internal/agent/httpsender/httpSender.go
> +package httpsender
осталось название файла поправить

2023-11-08 17:06 UTC, maybecoding commented on internal/agent/httpsender/httpSender.go
> +package httpsender
Сорян, поправил

2023-11-08 18:49 UTC, merged